org: matiascastillo
service: api-alumnos

provider:
  name: aws
  runtime: python3.12
  iam:
    role: arn:aws:lambda:us-east-1:153324968039:function:Listaralumnos

functions:
  listar:
    handler: Listaralumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda



